name: MSSQL CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t mssql .

      - name: Test Docker Image
        run: |
          docker run --rm mssql /bin/bash -c "echo 'Database container is running'"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.MSSQL }}" | docker login -u "saralaaa" --password-stdin

      - name: Tag Docker Image
        run: docker tag mssql saralaaa/myproject:latest

      - name: Push Docker Image to Docker Hub
        run: docker push saralaaa/myproject:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.MSSQL }}" | docker login -u "saralaaa" --password-stdin

      - name: Pull Docker Image
        run: docker pull saralaaa/myproject:latest

      - name: Deploy Docker Image
        run: |
          docker run -d -p 1433:1433 --name myproject saralaaa/myproject:latest
