name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t myproject .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.MSSQL }}" | docker login -u "saralaaa" --password-stdin

      - name: Tag Docker Image
        run: docker tag myproject:latest saralaaa/myproject:latest

      - name: Push Docker Image to Docker Hub
        run: docker push saralaaa/myproject:latest
